# Generated by Django 5.2.6 on 2025-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(upload_to='receipts/', verbose_name='Скриншот чека'),
        ),
    ]
