# Generated by Django 5.2.6 on 2025-09-24 07:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('text_input', 'Ввод текста'), ('textarea_input', 'Ввод Эссе'), ('fill_blanks', 'Текст с пропусками')], max_length=255, verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(help_text='Формат: {"blank1": "is", "blank2": "are", ...}', verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Используй {{blank1}}, {{blank2}}, ... для пропусков', verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='user_answer',
            field=models.JSONField(help_text='Формат: {"blank1": "is", "blank2": "are"}', verbose_name='Ответ пользователя'),
        ),
    ]
