# Generated by Django 5.2.6 on 2025-09-26 11:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.CharField(blank=True, help_text='Например: Заполни пропуски правильной формой глагола.', max_length=255, null=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(help_text='Формат: {"blank1": ["I am", "I\'m"], "blank2": ["is", "are"], ...}', verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Используй {{blank1}}, {{blank2}}, ... для пропусков', verbose_name='Текст вопроса'),
        ),
    ]
