# Generated by Django 5.2.6 on 2025-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_question_instruction_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instruction',
            field=models.CharField(blank=True, help_text='Например: Заполни пропуски правильной формой глагола.', max_length=255, null=True, verbose_name='Задание'),
        ),
    ]
