# Generated by Django 5.2.6 on 2025-09-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_exercise_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='instruction',
        ),
    ]
