# Generated by Django 5.2.6 on 2025-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_remove_question_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapter',
            name='completion_score',
            field=models.FloatField(default=0.0, verbose_name='Процент выполнения'),
        ),
    ]
