# Generated by Django 5.2.6 on 2025-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_userchapter_completion_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userchapter',
            index=models.Index(fields=['user', 'chapter'], name='users_and_c_user_id_bdc4b7_idx'),
        ),
    ]
