# Generated by Django 5.2.6 on 2025-10-05 07:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_userchapter_users_and_c_user_id_bdc4b7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
    ]
