# Generated by Django 5.2.6 on 2025-10-05 07:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
    ]
