# Generated by Django 5.2.6 on 2025-10-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
