# Generated by Django 5.2.6 on 2025-10-08 05:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='raw_answers',
            field=models.TextField(blank=True, help_text='Формат: blank1: answer1, answer2\nblank2: answer3\n... (по одному пропуску на строку)', verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(blank=True, help_text='Автоматически формируется из поля "Правильные ответы".', null=True, verbose_name='Правильные ответы (JSON)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Используйте ___ для обозначения пропусков (например: "I ___ a student.").', verbose_name='Текст вопроса'),
        ),
    ]
