# Generated by Django 5.2.6 on 2025-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0014_question_raw_answers_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Используйте ___ для обозначения пропусков (например: "I ___ a student.").', verbose_name='Текст вопроса'),
        ),
    ]
