# Generated by Django 5.2.6 on 2025-10-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video_path',
        ),
    ]
