# Generated by Django 5.2.6 on 2025-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_remove_topic_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
