# Generated by Django 5.2.6 on 2025-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0017_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
