# Generated by Django 5.2.6 on 2025-10-26 13:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0019_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Если отмечено, глава доступна только с оплаченным тарифом', verbose_name='Платная глава'),
        ),
        migrations.AlterField(
            model_name='coursetariff',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым или 0 для бесплатного тарифа', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Скриншот чека'),
        ),
    ]
