# Generated by Django 5.2.6 on 2025-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0020_chapter_is_paid_alter_coursetariff_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеоурок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
